# Generated by Django 5.1.6 on 2025-02-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
