# Generated by Django 5.1.6 on 2025-02-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TransactionId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(blank=True, max_length=3, unique=True)),
                ('TransactionType', models.CharField(choices=[('borrowed', 'Borrowed'), ('returned', 'Returned')], max_length=10)),
                ('DateOfBorrowed', models.DateField(auto_now_add=True)),
                ('DueDate', models.DateField()),
                ('BookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
