# Generated by Django 5.1.4 on 2025-02-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='BookId',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='DateOfBorrowed',
            new_name='date_of_borrowed',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='DueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='StudentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionId',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionType',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='UserId',
            new_name='user_id',
        ),
    ]
