# Generated by Django 5.1.4 on 2025-02-15 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_bookid_transaction_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_of_borrowed',
            new_name='date_borrowed',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 3, 17)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
