# Generated by Django 5.1.4 on 2025-02-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_date_of_borrowed_transaction_date_borrowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='UserId',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(),
        ),
    ]
