# Generated by Django 5.1.4 on 2025-02-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_transaction_id_transaction_transactionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='student',
            new_name='student_id',
        ),
    ]
