# Generated by Django 5.1.4 on 2025-02-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_book_transaction_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='date_borrowed',
            new_name='date_of_borrowed',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='TransactionId',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='UserId',
            new_name='user_id',
        ),
    ]
