# Generated by Django 5.1.4 on 2025-02-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rename_date_borrowed_transaction_date_of_borrowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(max_length=3),
        ),
    ]
