# Generated by Django 5.1.6 on 2025-02-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('ContactNumber', models.CharField(max_length=15, unique=True)),
                ('Department', models.CharField(max_length=255)),
            ],
        ),
    ]
