# Generated by Django 5.1.4 on 2025-02-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
