# Generated by Django 5.1.4 on 2025-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_studentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='StudentId',
            new_name='student_id',
        ),
    ]
